import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import toast from 'react-hot-toast';
import { Link } from 'react-router-dom';
import { http } from '../api/http.js';

export default function CustomersPage() {
  const queryClient = useQueryClient(); const [open, setOpen] = useState(false); const [form, setForm] = useState({ name: '', email: '', company: '' });
  const customers = useQuery({ queryKey: ['customers'], queryFn: () => http.get('/customers').then((response) => response.data.customers) });
  const create = useMutation({ mutationFn: (data) => http.post('/customers', data), onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['customers'] }); setOpen(false); setForm({ name: '', email: '', company: '' }); toast.success('Customer created.'); }, onError: (error) => toast.error(error.response?.data?.message || 'Unable to create customer.') });
  function submit(event) { event.preventDefault(); create.mutate(form); }
  return <div><div className="flex items-end justify-between"><div><p className="text-sm font-medium text-blue-700">Customer management</p><h2 className="mt-1 text-3xl font-bold">Customers</h2></div><button onClick={() => setOpen(!open)} className="rounded bg-blue-600 px-4 py-2 font-medium text-white">{open ? 'Close' : 'New customer'}</button></div>{open && <form onSubmit={submit} className="mt-6 grid gap-3 rounded-xl bg-white p-5 shadow-sm md:grid-cols-3"><input required placeholder="Name" className="rounded border p-2" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /><input required type="email" placeholder="Email" className="rounded border p-2" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} /><input placeholder="Company" className="rounded border p-2" value={form.company} onChange={(e) => setForm({ ...form, company: e.target.value })} /><button disabled={create.isPending} className="rounded bg-slate-900 px-4 py-2 text-white md:col-span-3">{create.isPending ? 'Saving…' : 'Create customer'}</button></form>}<div className="mt-6 overflow-hidden rounded-xl bg-white shadow-sm"><table className="w-full text-left"><thead className="bg-slate-50 text-sm text-slate-500"><tr><th className="px-5 py-3">Customer</th><th className="px-5 py-3">Company</th><th className="px-5 py-3">Health</th></tr></thead><tbody>{customers.isLoading ? <tr><td className="px-5 py-5" colSpan="3">Loading customers…</td></tr> : customers.data?.length ? customers.data.map((customer) => <tr className="border-t" key={customer._id}><td className="px-5 py-4"><Link className="font-medium text-blue-700 hover:underline" to={`/customers/${customer._id}`}>{customer.name}</Link><p className="text-sm text-slate-500">{customer.email}</p></td><td className="px-5 py-4">{customer.company || '—'}</td><td className="px-5 py-4"><span className="rounded-full bg-blue-50 px-2 py-1 text-sm text-blue-700">{customer.healthScore}</span></td></tr>) : <tr><td className="px-5 py-5" colSpan="3">No customers yet.</td></tr>}</tbody></table></div></div>;
}
