import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import toast from 'react-hot-toast';
import { http } from '../api/http.js';

export default function EmailsPage() {
  const queryClient = useQueryClient(); const [open, setOpen] = useState(false); const [values, setValues] = useState({ sender: '', subject: '', body: '', customerId: '' });
  const emails = useQuery({ queryKey: ['emails'], queryFn: () => http.get('/emails').then((response) => response.data.emails) });
  const process = useMutation({ mutationFn: (payload) => http.post('/emails/process', { ...payload, customerId: payload.customerId || undefined }), onSuccess: () => { queryClient.invalidateQueries(); setValues({ sender: '', subject: '', body: '', customerId: '' }); setOpen(false); toast.success('Email processed and routed to NxtBiz agents.'); }, onError: (error) => toast.error(error.response?.data?.message || 'Unable to process email.') });
  return <div><div className="flex items-end justify-between"><div><p className="text-sm font-medium text-blue-700">Email intelligence</p><h2 className="mt-1 text-3xl font-bold">Email dashboard</h2></div><button className="rounded bg-blue-600 px-4 py-2 font-medium text-white" onClick={() => setOpen(!open)}>{open ? 'Close' : 'Process incoming email'}</button></div>{open && <form className="mt-6 grid gap-4 rounded-xl bg-white p-5 shadow-sm" onSubmit={(event) => { event.preventDefault(); process.mutate(values); }}><div className="grid gap-4 md:grid-cols-2"><label className="text-sm font-medium">Sender<input required type="email" className="mt-1 w-full rounded border p-2" value={values.sender} onChange={(event) => setValues({ ...values, sender: event.target.value })} /></label><label className="text-sm font-medium">Customer ID (optional)<input className="mt-1 w-full rounded border p-2" value={values.customerId} onChange={(event) => setValues({ ...values, customerId: event.target.value })} /></label></div><label className="text-sm font-medium">Subject<input required className="mt-1 w-full rounded border p-2" value={values.subject} onChange={(event) => setValues({ ...values, subject: event.target.value })} /></label><label className="text-sm font-medium">Body<textarea required className="mt-1 min-h-28 w-full rounded border p-2" value={values.body} onChange={(event) => setValues({ ...values, body: event.target.value })} /></label><button disabled={process.isPending} className="rounded bg-slate-900 px-4 py-2 font-medium text-white">{process.isPending ? 'Processing…' : 'Analyze and orchestrate'}</button></form>}<div className="mt-6 overflow-x-auto rounded-xl bg-white shadow-sm"><table className="w-full text-left"><thead className="bg-slate-50 text-sm text-slate-500"><tr><th className="px-5 py-3">Email</th><th className="px-5 py-3">Intent</th><th className="px-5 py-3">Sentiment</th><th className="px-5 py-3">Urgency</th><th className="px-5 py-3">Status</th></tr></thead><tbody>{emails.isLoading ? <tr><td colSpan="5" className="px-5 py-5">Loading emails…</td></tr> : emails.data?.length ? emails.data.map((email) => <tr className="border-t" key={email._id}><td className="px-5 py-4"><p className="font-medium">{email.subject}</p><p className="text-sm text-slate-500">{email.sender}</p></td><td className="px-5 py-4">{email.intent}</td><td className="px-5 py-4">{email.sentiment}</td><td className="px-5 py-4">{email.urgency}</td><td className="px-5 py-4">{email.processed ? 'Processed' : 'Pending'}</td></tr>) : <tr><td colSpan="5" className="px-5 py-5">No emails processed yet.</td></tr>}</tbody></table></div></div>;
}
