import express from 'express';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import helmet from 'helmet';
import cors from 'cors';
import compression from 'compression';
import cookieParser from 'cookie-parser';
import morgan from 'morgan';
import { env } from './config/env.js';
import authRoutes from './modules/auth/auth.routes.js';
import usersRoutes from './modules/users/users.routes.js';
import customersRoutes from './modules/customers/customers.routes.js';
import crmRoutes from './modules/crm/crm.routes.js';
import dashboardRoutes from './modules/dashboard/dashboard.routes.js';
import meetingsRoutes from './modules/meetings/meetings.routes.js';
import ticketsRoutes from './modules/tickets/tickets.routes.js';
import invoicesRoutes from './modules/invoices/invoices.routes.js';
import reportsRoutes from './modules/reports/reports.routes.js';
import emailsRoutes from './modules/emails/emails.routes.js';
import agentsRoutes from './modules/agents/agents.routes.js';
import notificationsRoutes from './modules/notifications/notifications.routes.js';
import memoryRoutes from './modules/memory/memory.routes.js';
import workflowsRoutes from './modules/workflows/workflows.routes.js';

export const app = express();
app.use(helmet());
app.use(cors({ origin: env.clientOrigin, credentials: true }));
app.use(compression());
app.use(express.json({ limit: '1mb' }));
app.use(cookieParser());
app.use(morgan(env.nodeEnv === 'production' ? 'combined' : 'dev'));
app.get('/health', (_req, res) => res.json({ status: 'ok', service: 'NxtBiz' }));
app.use('/pdfs', express.static(path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', 'storage', 'pdfs')));
app.use('/api/auth', authRoutes);
app.use('/api/users', usersRoutes);
app.use('/api/dashboard', dashboardRoutes);
app.use('/api/customers', customersRoutes);
app.use('/api/crm', crmRoutes);
app.use('/api/meetings', meetingsRoutes);
app.use('/api/invoices', invoicesRoutes);
app.use('/api/tickets', ticketsRoutes);
app.use('/api/reports', reportsRoutes);
app.use('/api/emails', emailsRoutes);
app.use('/api/agents', agentsRoutes);
app.use('/api/notifications', notificationsRoutes);
app.use('/api/memory', memoryRoutes);
app.use('/api/workflows', workflowsRoutes);
app.use((_req, res) => res.status(404).json({ message: 'Route not found.' }));
app.use((error, _req, res, _next) => {
  console.error(error);
  res.status(error.status || 500).json({ message: env.nodeEnv === 'production' ? 'Internal server error.' : error.message });
});
