import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import PDFDocument from 'pdfkit';
import { env } from '../config/env.js';
const outputDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..', 'storage', 'pdfs');
const safe = (value) => String(value).replace(/[^a-z0-9_-]/gi, '_');
async function writePdf(filename, render) { await fs.promises.mkdir(outputDir, { recursive: true }); const filePath = path.join(outputDir, filename); await new Promise((resolve, reject) => { const document = new PDFDocument({ margin: 48 }); const stream = fs.createWriteStream(filePath); document.pipe(stream); stream.on('finish', resolve); stream.on('error', reject); render(document); document.end(); }); return `${env.pdfBaseUrl || '/pdfs'}/${filename}`; }
export function generateInvoicePdf(invoice, customer) { const filename = `invoice-${safe(invoice.id)}.pdf`; return writePdf(filename, (doc) => { doc.fontSize(24).text('NxtBiz Invoice'); doc.moveDown(); doc.fontSize(12).text(`Invoice ID: ${invoice.id}`); doc.text(`Customer: ${customer?.name || 'Unknown customer'}`); doc.text(`Due date: ${new Date(invoice.dueDate).toLocaleDateString()}`); doc.text(`Amount due: ${invoice.amount}`); doc.moveDown(); doc.text('Line items'); (invoice.lineItems || []).forEach((item) => doc.text(`${item.description} — ${item.quantity} × ${item.unitPrice}`)); doc.moveDown(); doc.text('Generated by NxtBiz business operations platform.'); }); }
export function generateReportPdf(report) { const filename = `report-${safe(report.id)}.pdf`; return writePdf(filename, (doc) => { doc.fontSize(24).text(report.title); doc.moveDown(); doc.fontSize(12).text(report.summary); doc.moveDown(); doc.text('Metrics'); Object.entries(report.metrics || {}).forEach(([key, value]) => doc.text(`${key}: ${value}`)); doc.moveDown(); doc.text('Recommendations'); (report.recommendations || []).forEach((item) => doc.text(`• ${item}`)); }); }
